### PR TITLE
Add code spell check github workflow

### PR DESCRIPTION
**Pull request by Okabe-Rintarou-0**
**What type of PR is this?**
feature

**What this PR does / why we need it**:
Current there are many spelling errors in kmesh, we need an automatic way to check spelling errors.

We can config what we don't need to check in .codespellrc.
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by Okabe-Rintarou-0** [comment]
I also use this action in my repo. The check process is very rapid. It will not affect other CI/CD.

**Comment by Okabe-Rintarou-0** [comment]
should ignore codecov here.

**Review by hzxuzhonghu — COMMENTED** [review]
Can we use golangcilint misspell https://golangci-lint.run/usage/linters/#misspell.

**Comment by Okabe-Rintarou-0** [comment]
> Can we use golangcilint misspell https://golangci-lint.run/usage/linters/#misspell.

Maybe it just check the misspell of go files? There are some typo errors in .c files too. Some of them are even fatal, like using `defalut` instead of `default` in switch.

**Comment by hzxuzhonghu** [comment]
Good to know, make sense then

**Review by hzxuzhonghu — APPROVED** [review]
/lgtm

**Comment by Okabe-Rintarou-0** [comment]
@hzxuzhonghu This patch fix many typo errors which should not be tested. So the codecov should be ignored here.

**Pull request merged**
