### PR TITLE
use dataplane label to manage workloads

### PR DESCRIPTION
**Pull request by YaoZengzeng**
**What type of PR is this?**

/kind enhancement

**What this PR does / why we need it**:

Add basic test case for Kmesh manage.

**Which issue(s) this PR fixes**:
Fixes part of #614

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by YaoZengzeng** [comment]
@hzxuzhonghu PTAL

**Review by hzxuzhonghu — APPROVED** [review]
/lgtm

**Pull request merged**
