### PR TITLE
add E2E test "TestServiceEntrySelectsWorkloadEntry"

### PR DESCRIPTION
**Pull request by YaoZengzeng**
**What type of PR is this?**

/kind enhancement

**What this PR does / why we need it**:

Test that ServiceEntry and WorkloadEntry are different resource objects and SE selects WE through selector.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
Can you add some description about what is being tested? Only only a general title testing SE

**Comment by YaoZengzeng** [comment]
@hzxuzhonghu updated

**Comment by YaoZengzeng** [comment]
ping @hzxuzhonghu

**Review by hzxuzhonghu — COMMENTED** [review]
I am thinking that this test sceanrio has nothing to do with kmesh, none of  kmesh components take part in the traffic flow, correct me if i missed anything

**Comment by YaoZengzeng** [comment]
> I am thinking that this test sceanrio has nothing to do with kmesh, none of kmesh components take part in the traffic flow, correct me if i missed anything

Both ServiceEntry and WorkloadEntry are converted to eBPF config through workload API and traffic is forwarded to the ingress gateway through eBPF. As we discussed before, Kmesh can't handle the situation where the `target port` is not set in the ServiceEntry. If the `target port` config in this test is deleted, the test will not pass, which also shows that the traffic has been processed by Kmesh.

**Comment by YaoZengzeng** [comment]
> I am thinking that this test sceanrio has nothing to do with kmesh, none of kmesh components take part in the traffic flow, correct me if i missed anything

The ingress in the middle seems to solve this issue https://github.com/istio/istio/issues/45942 , don't know whether Kmesh will have the same problem. @hzxuzhonghu

**Comment by hzxuzhonghu** [comment]
I donot quite understand, can we talk directly on line

**Comment by YaoZengzeng** [comment]
@hzxuzhonghu updated

**Review by hzxuzhonghu — APPROVED** [review]
/lgtm

Just one confusion. does a SE with ipv6 selects ipv4 wle?

**Pull request merged**
