### PR TITLE
add configuration to collect the Prometheus metrics from Kmesh and rename them into a format that Kiali can read.

### LINKED ISSUE #1033: Improve the compatibility of Kmesh observability with the Istio ecosystem
**Task description**:
1. Currently, the names of kmesh's observability metrics begin with "kmesh," such as "kmesh_tcp_workload_sent_bytes_total". This could break some software in Istio Ecosystem such as kiali, which shows mesh topology graph based on Istio standard metrics like "istio_tcp_sent_bytes_total"

**Who can join or take the task**:

The good first issue is intended for `first-time contributors` to get started on his/her contributor journey.

After a contributor has successfully completed 1-2 good first issue's,
they should be ready to move on to `help wanted` items, saving the remaining `good first issue` for other new contributors.

**How to join or take the task**:

Just reply on the issue with the message `/assign` in a separate line.

Then, the issue will be assigned to you.

**How to ask for help**:

If you need help or have questions, please feel free to ask on this issue.
The issue author or other members of the community will guide you through the contribution process.

### PR DESCRIPTION
**Pull request by delavet**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

This PR supplies a new Prometheus configuration file in Kmesh samples. Compared with the origin one in `samples/addons/prometheus.yaml`, this new Prometheus configuration file adds some modifications to help Kiali drawing Traffic Graph based on metrics generated by Kmesh.
- Add some recording rules which rename the Kmesh service tcp metrics to Istio standard tcp metrics. This makes Kiali recognize these tcp metrics and draw tcp-based Traffic Graph.
- Besides, a metrics relabel config is added to the scrap_configs, in order to rename the `reporter=waypoint` label to `reporter=destination`. Through this relabel config, Kiali can read http metrics exposed by waypoint without having to recognize that the data plane is in Ambient Mode. In this way, Kiali can draw http Traffic Graph when data plane mode is Kmesh. 

A document utilizing this prometheus configuration file to visualize Traffic Graph in Kiali under Kmesh will be given later.

**Which issue(s) this PR fixes**:
Fixes #1033

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
No, this just supplies a sample prometheus configuration which will be used in documentations.

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
@delavet How is the graph drawn by kiali look like now  with the config

**Comment by delavet** [comment]
> @delavet What does the graph drawn by kiali look like now with the config

I just got some update here. The Prometheus configuration file is updated and with this configuration we can get a pretty decent traffic graph like this.
 
image

We can see there are blue edges (tcp traffics) between services whose traffics are proxied by Kmesh, and green edges (http traffics) between services whose traffics are proxied by Waypoint.

The service node name seems not behavior the same as Istio standard metrics. I have just submitted a new issue to track this here:  #1089

**Review by hzxuzhonghu — APPROVED** [review]
Cool

/lgtm

**Comment by LiZhenCheng9527** [comment]
so, is the kiali configuration consistent with `samples/addons/kiali.yaml` in istio repo?

**Comment by delavet** [comment]
> so, is the kiali configuration consistent with `samples/addons/kiali.yaml` in istio repo?

not exactly the same. Actually, I use helm to install kiali following https://kiali.io/docs/installation/installation-guide/install-with-helm/.

However, I believe the only difference is the external_service config in the kiali ConfigMap. This is because we should make kiali read Prometheus deployed in kmesh-system.

I prefer to use helm and adjust some values in the later documentation.

**Pull request merged**
