### PR TITLE
A ut of cni plugin

### PR DESCRIPTION
**Pull request by LiZhenCheng9527**
**What type of PR is this?**
/kind enhancement

**What this PR does / why we need it**:
a part of #104

### CODE REVIEW

**Comment by LiZhenCheng9527** [comment]
**Note**: This PR is just an example of Kmesh UT for now.
I will improve the UT of the functions and methods in this Go file later.
/hold

**Comment by hzxuzhonghu** [comment]
>time="[20](https://github.com/kmesh-net/kmesh/actions/runs/8135459431/job/22230036362?pr=143#step:8:21)24-03-04T03:43:12Z" level=fatal msg="failed to create log directory"


```
	err := os.MkdirAll(path, 0o700)
	if err != nil {
		logger.Fatal("failed to create log directory")
	}
```

It seems the permission is not allowed. We should update the logger

**Review by hzxuzhonghu — APPROVED** [review]
/lgtm

Approve first, but we shouldn't require run ut with sudo priv

**Pull request merged**
