### PR TITLE
add E2E test for istio 1.24 to CI

### PR DESCRIPTION
**Pull request by YaoZengzeng**
**What type of PR is this?**

/kind enhancement

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Review by hzxuzhonghu — COMMENTED** [review]
Is that safe it always use ghcr.io/kmesh-net/waypoint:latest

**Comment by YaoZengzeng** [comment]
> Is that safe it always use ghcr.io/kmesh-net/waypoint:latest

We should use `latest` image in main branch and use corresponding release image in the release branch.

**Review by hzxuzhonghu — APPROVED** [review]
Yeah, that's the right way

**Pull request merged**
