### PR TITLE
Ratelimit bug fix.

### PR DESCRIPTION
**Pull request by yuanqijing**
**What type of PR is this?**
fix ratelimit compile failed on oe.

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Review by hzxuzhonghu — DISMISSED** [review]
This fix is good, not sure have you tested it.

**Comment by tacslon** [comment]
Need some testing on enhanced kernel, otherwise LGTM.

**Comment by yuanqijing** [comment]
test on openEuler 2303:
before:
image

after:
image

**Review by hzxuzhonghu — APPROVED** [review]
/lgtm

**Pull request merged**
