### PR TITLE
Downgrade go version to v1.21.4

### PR DESCRIPTION
**Pull request by tacslon**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
Downgrade go version to v1.21.4
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by hzxuzhonghu — CHANGES_REQUESTED** [review]
Downgrade go version is not a common op, unless the current version has serious problem

**Comment by YaoZengzeng** [comment]
Also E2E test framework depends on a very new version of istio, which uses go 1.22, so go 1.21 may not work and CI does fail.

**Pull request closed without merging**
