### PR TITLE
Fix the Enhanced Compilation Failure Issue

### PR DESCRIPTION
**Pull request by lec-bit**
**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Review by hzxuzhonghu — APPROVED** [review]
Thanks @lec-bit 

/lgtm

**Comment by bfforever** [comment]
https://github.com/kmesh-net/kmesh/blob/92ec79142f6c7d56eaafce9fa303108c822fe9df/pkg/bpf/bpf_kmesh.go#L83
https://github.com/kmesh-net/kmesh/blob/92ec79142f6c7d56eaafce9fa303108c822fe9df/pkg/bpf/bpf_kmesh.go#L86
Maybe above two place need to change  `Bpfmesh` to reference type to fix enhanced complilation failure.

**Comment by hzxuzhonghu** [comment]
In theory this is better to return pointer type in case there is some copy and we mutate the original object later . @lec-bit @bfforever Did you test the features with this patch, i canot see where we copy it

**Comment by bfforever** [comment]
My development machine is enhanced kernel, `go build ` would build with bpf_kmesh.go file, not bpf_kmesh_l4.go file, so would report a `inconsistent type error` at compile time.

**Pull request merged**
