### PR TITLE
use go vendor mode

### LINKED ISSUE #480: manage ‘go dependency packages’ in vendor mode, and compilation can be performed on a machine without network connection.
**What would you like to be added**:

**Why is this needed**:

### PR DESCRIPTION
**Pull request by kwb0523**
**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #480 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by LiZhenCheng9527** [comment]
please add vendor to gitignore

**Comment by kwb0523** [comment]
> please add vendor to gitignore

we need add vendor, should be tracked by git. we can add vendor in .gitignore with another commit.

**Pull request closed without merging**
