### PR TITLE
add kmesh custom grafana addon

### PR DESCRIPTION
**Pull request by YaoZengzeng**
**What type of PR is this?**

/kind enhancement

**What this PR does / why we need it**:

Add Kmesh custom grafana addon to display service metrics 

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by LiZhenCheng9527** [comment]
#688

**Comment by YaoZengzeng** [comment]
@hzxuzhonghu PTAL

**Review by hzxuzhonghu — APPROVED** [review]
/lgtm

**Pull request merged**
