### PR TITLE
bump dependency

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
And remove vendor

### CODE REVIEW

**Comment by nlgwcy** [comment]
Good Job! 
Please attach the [mini_test](https://github.com/kmesh-net/kmesh/tree/main/test#%E5%A6%82%E4%BD%95%E8%BF%9B%E8%A1%8Ckmesh%E6%B5%8B%E8%AF%95) execution result to the PR to ensure that the basic functions are normal. Thank you.

**Comment by hzxuzhonghu** [comment]
@lec-bit can you help run this test

**Comment by lec-bit** [comment]
Thu Jan 11 16:34:55 2024 - INFO  - 配置文件加载完成...
Thu Jan 11 16:34:56 2024 - INFO  - start to run testcase:oe_test_base_function.
Thu Jan 11 16:35:11 2024 - INFO  - The case exit by code 0.
Thu Jan 11 16:35:11 2024 - INFO  - End to run testcase:oe_test_base_function.
Thu Jan 11 16:35:11 2024 - INFO  - start to run testcase:oe_test_dark_launch_function.
Thu Jan 11 16:35:24 2024 - INFO  - The case exit by code 0.
Thu Jan 11 16:35:24 2024 - INFO  - End to run testcase:oe_test_dark_launch_function.
Thu Jan 11 16:35:24 2024 - INFO  - start to run testcase:oe_test_service_function.
Thu Jan 11 16:37:20 2024 - INFO  - The case exit by code 0.
Thu Jan 11 16:37:20 2024 - INFO  - End to run testcase:oe_test_service_function.
Thu Jan 11 16:37:20 2024 - INFO  - start to run testcase:oe_test_tcp_proxy_weight_cluster_function.
Thu Jan 11 16:37:35 2024 - INFO  - The case exit by code 0.
Thu Jan 11 16:37:35 2024 - INFO  - End to run testcase:oe_test_tcp_proxy_weight_cluster_function.
Thu Jan 11 16:37:35 2024 - INFO  - start to run testcase:oe_test_route_function.
Thu Jan 11 16:37:47 2024 - INFO  - The case exit by code 0.
Thu Jan 11 16:37:47 2024 - INFO  - End to run testcase:oe_test_route_function.
Thu Jan 11 16:37:47 2024 - INFO  - start to run testcase:oe_test_lb_policy_function.
Thu Jan 11 16:37:58 2024 - INFO  - The case exit by code 0.
Thu Jan 11 16:37:58 2024 - INFO  - End to run testcase:oe_test_lb_policy_function.
Thu Jan 11 16:37:58 2024 - INFO  - A total of 6 use cases were executed, with 6 successes and 0 failures.
The following test cases run success
--------------------------------------->
oe_test_base_function
oe_test_dark_launch_function
oe_test_lb_policy_function
oe_test_route_function
oe_test_service_function
oe_test_tcp_proxy_weight_cluster_function
<---------------------------------------
****************************************
NOTICE:The test cases execution log is recorded in mugen-master/logs/kmesh/
****************************************
   UNINSTALL //usr/lib64/libkmesh_api_v2_c.so
   UNINSTALL //usr/lib64/libkmesh_deserial.so
rm -rf /lib/modules/`uname -r`/kmesh.ko
rm -rf /lib/modules/kmesh
depmod -a
   UNINSTALL //usr/bin/kmesh-daemon
   UNINSTALL //usr/bin/kmesh-cmd
   UNINSTALL //usr/bin/mdacore

**Pull request merged**
