### PR TITLE
[cherry-pick 0.4] add service metrics

### LINKED ISSUE #701: [release-0.4] Add service metric and use ringbuf to report metrics
Manual cherrypick required.

#688 failed to apply on top of branch "release-0.4":
```
Applying: Unified reporting of metrics/logs: remove metrics report
Using index info to reconstruct a base tree...
M	bpf/kmesh/probes/metrics.h
M	bpf/kmesh/probes/probe.h
Falling back to patching base and 3-way merge...
Auto-merging bpf/kmesh/probes/probe.h
CONFLICT (modify/delete): bpf/kmesh/probes/metrics.h deleted in Unified reporting of metrics/logs: remove metrics report and modified in HEAD. Version HEAD of bpf/kmesh/probes/metrics.h left in tree.
error: Failed to merge in the changes.
hint: Use 'git am --show-current-patch=diff' to see the failed patch
Patch failed at 0001 Unified reporting of metrics/logs: remove metrics report
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".

```

### PR DESCRIPTION
**Pull request by LiZhenCheng9527**
**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #701 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
is the workload nil check included?

**Comment by LiZhenCheng9527** [comment]
> is the workload nil check included?

included

**Review by hzxuzhonghu — APPROVED** [review]
/lgtm

**Pull request merged**
