### PR TITLE
Prevent potential panic when object is nil or empty

### LINKED ISSUE #875: Another potential ads deserial bug
**What happened**:
```go
func socketAddressToClang(goMsg *core_v2.SocketAddress) (*C.Core__SocketAddress, error) {
	buf, err := proto.Marshal(goMsg)
	if err != nil {
		return nil, err
	}

	cMsg := C.core__socket_address__unpack(nil, C.size_t(len(buf)), convertToPack(buf))
	if cMsg == nil {
		return nil, fmt.Errorf("core__socket_address__unpack failed")
	}
	return cMsg, nil
}
```

take the above code as example, if the field of goMsg is all zero, proto.Marshal will produce a buf with zero length.
then convertToPack will cause panic.

cc @hzxuzhonghu @nlgwcy 

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kmesh version:
- Others:

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #875

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
cc @Okabe-Rintarou-0 How about this fix?

**Comment by Okabe-Rintarou-0** [comment]
> cc @Okabe-Rintarou-0 How about this fix?

seems good

**Pull request merged**
